name: Deploy to Namecheap Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Namecheap Hosting
        run: |
          ftp -p -inv server230.web-hosting.com << EOF
          cd public_html  # Adjust the path based on your hosting setup
          put -r *          # Upload all files recursively
          quit
          EOF
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
